name: personal_web_site

packages:
  - packages/**
  - app/**

scripts:
  generate_and_build:
    run: |
      melos clean
      melos bs
      melos generate:spider
      melos generate:build_runner

  analyze:
    run: melos exec -- dart analyze .
    description: Run `dart analyze` in all packages.

  analyze:custom_lint:
    run: melos exec -- dart run custom_lint
  description: Run `dart custom_lint ` in all packages.

  remove_unused_import:
    run: melos exec -- dart fix --apply --code=unused_import
    description: remove unused import in all file.

  generate:spider:
    run: |
      flutter pub get
      melos exec --depends-on="spider" -- spider build
    description: Run spider to generate resources.

  generate:build_runner:
    run: melos exec --depends-on="build_runner" -- "dart run build_runner build -d"
    description: Build all generated files for Dart & Flutter packages in this project.


command:
  bootstrap:
    environment:
      sdk: ">=3.4.3 <4.0.0"
      flutter: ">=3.0.0 <4.0.0"
    dependencies:

    dev_dependencies:
      flutter_lints: ^4.0.0
